#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Medical.Resource", IsApplication=true)]

namespace Medical
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000b
			public const int fontPath = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int mainColor = 2130771980;
			
			// aapt resource value: 0x7f010001
			public const int max = 2130771969;
			
			// aapt resource value: 0x7f01000a
			public const int numberProgressBarStyle = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int progress = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int progress_reached_bar_height = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int progress_reached_color = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int progress_text_color = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int progress_text_offset = 2130771976;
			
			// aapt resource value: 0x7f010006
			public const int progress_text_size = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int progress_text_visibility = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int progress_unreached_bar_height = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int progress_unreached_color = 2130771970;
			
			// aapt resource value: 0x7f01000d
			public const int secondaryColor = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090004
			public const int ColorBtn = 2131296260;
			
			// aapt resource value: 0x7f090008
			public const int ColorLYTCBP = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int ColorTmAb = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int Cus = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int MinOR = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int OrangeRed = 2131296261;
			
			// aapt resource value: 0x7f090000
			public const int Red = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int WDC = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int White = 2131296257;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AgAlarm = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AgCBP = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AgCycle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int AgHR = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int AgMsg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int AgSetpCounter = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int AgTest = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int AgWatchSmart = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int AM = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BlackDel = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int BlackHeartRateHR = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int BlackHeartRateInfo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CaiTea = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Caleri = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Caloric = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int CBP = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int CBPCafi = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int CBPFood = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int CBPSleep = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int CBPSport = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int CBPSportRed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int CBPWater = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int CMActivity = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int CMAge = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int CMCancel = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int CMHeight = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int CmNo = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int CMOK = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int CMSex = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int CMWeight = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int CmYes = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int CPBHeartRateBlood = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int CPBHome = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int CPBReport = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int CPBWeight = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int DarshbordK = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Dashboard = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int DefAccount = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int DelPF = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int DelSS = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Error = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Food = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Girl = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int gvAlarm = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int gvCBP = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int gvCycle = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int gvHR = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int gvMsg = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int gvSetpCounter = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int gvTagZ = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int gvTest = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int gvWatchSmart = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Health = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int HealthCal = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int HealthHeight = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int HealthKhMeter = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int HealthNotiSp = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int HealthSpeed = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int HealthStepCounter = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int HealthTimer = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Heart = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int HeartRateHRCount = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int HeartRateMonitor = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int HeartRateNoti = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int HeartRateSoNv = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int HeightS = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int HelpRA = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int HR = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int HR450 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int HR470 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int HR490 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int HR520 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int HRBBloodPre = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int HRBHeartRate = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int HRCardiogram = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ic_checked_mark = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ic_failure_mark = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int InfoApp = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int Man = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int MCDep = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int MCHome = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int MCSB = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int MedicalApp = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int MetalDetector = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int MG = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ReLoad = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int ReportFWCS = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int RgbHeartRateHR = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int RgbHeartRateInfo = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int Sensor = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int SetDataOK = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int Sleepy = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int SmartphoneVib = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int SP = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int SpeedD = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ST = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int StepCounterNoti = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int Timer = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int Water = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int WHTall = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int WHWeight = 2130837604;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080093
			public const int AHImageViewMain = 2131230867;
			
			// aapt resource value: 0x7f080094
			public const int AHScrollViewMp = 2131230868;
			
			// aapt resource value: 0x7f080095
			public const int AHTextViewSummery = 2131230869;
			
			// aapt resource value: 0x7f08004f
			public const int CBPActionMenuViewCafi = 2131230799;
			
			// aapt resource value: 0x7f080047
			public const int CBPActionMenuViewFood = 2131230791;
			
			// aapt resource value: 0x7f080053
			public const int CBPActionMenuViewSleep = 2131230803;
			
			// aapt resource value: 0x7f08004b
			public const int CBPActionMenuViewWater = 2131230795;
			
			// aapt resource value: 0x7f08005a
			public const int CBPButtonCalc = 2131230810;
			
			// aapt resource value: 0x7f080059
			public const int CBPButtonClaerData = 2131230809;
			
			// aapt resource value: 0x7f080061
			public const int CBPEditTextValueFWCS = 2131230817;
			
			// aapt resource value: 0x7f080051
			public const int CBPImageViewCafi = 2131230801;
			
			// aapt resource value: 0x7f080049
			public const int CBPImageViewFood = 2131230793;
			
			// aapt resource value: 0x7f080055
			public const int CBPImageViewSleep = 2131230805;
			
			// aapt resource value: 0x7f08004d
			public const int CBPImageViewWater = 2131230797;
			
			// aapt resource value: 0x7f080042
			public const int CBPInputDataSHWTEditTextKeyText = 2131230786;
			
			// aapt resource value: 0x7f080041
			public const int CBPInputDataSHWTEditTextKeyTitle = 2131230785;
			
			// aapt resource value: 0x7f080058
			public const int CBPLinearLayoutTPBtn = 2131230808;
			
			// aapt resource value: 0x7f080044
			public const int CBPLinearLayoutTp1 = 2131230788;
			
			// aapt resource value: 0x7f08005b
			public const int CBPLinearLayoutTp2 = 2131230811;
			
			// aapt resource value: 0x7f08005d
			public const int CBPLinearLayoutTp3 = 2131230813;
			
			// aapt resource value: 0x7f08005f
			public const int CBPLinearLayoutTp4 = 2131230815;
			
			// aapt resource value: 0x7f080056
			public const int CBPScrollViewMT = 2131230806;
			
			// aapt resource value: 0x7f080043
			public const int CBPTabHostMain = 2131230787;
			
			// aapt resource value: 0x7f080045
			public const int CBPTableLayoutMain = 2131230789;
			
			// aapt resource value: 0x7f08004e
			public const int CBPTableRowCafi = 2131230798;
			
			// aapt resource value: 0x7f080046
			public const int CBPTableRowFood = 2131230790;
			
			// aapt resource value: 0x7f080052
			public const int CBPTableRowSleep = 2131230802;
			
			// aapt resource value: 0x7f08004a
			public const int CBPTableRowWater = 2131230794;
			
			// aapt resource value: 0x7f080050
			public const int CBPTextViewCafi = 2131230800;
			
			// aapt resource value: 0x7f080048
			public const int CBPTextViewFood = 2131230792;
			
			// aapt resource value: 0x7f080054
			public const int CBPTextViewSleep = 2131230804;
			
			// aapt resource value: 0x7f080057
			public const int CBPTextViewVitaem = 2131230807;
			
			// aapt resource value: 0x7f08004c
			public const int CBPTextViewWater = 2131230796;
			
			// aapt resource value: 0x7f080062
			public const int CBPTimePickerSleepy = 2131230818;
			
			// aapt resource value: 0x7f080022
			public const int CMDepButtonAgainTest = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int CMDepButtonResult = 2131230755;
			
			// aapt resource value: 0x7f080021
			public const int CMDepLinearLayoutBtn = 2131230753;
			
			// aapt resource value: 0x7f08001f
			public const int CMDepLinearLayoutMain = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int CMDepListViewMain = 2131230752;
			
			// aapt resource value: 0x7f08003e
			public const int CMDiabetButtonCalc = 2131230782;
			
			// aapt resource value: 0x7f08003d
			public const int CMDiabetButtonClaer = 2131230781;
			
			// aapt resource value: 0x7f08002f
			public const int CMDiabetEditTextAge = 2131230767;
			
			// aapt resource value: 0x7f08002c
			public const int CMDiabetEditTextTall = 2131230764;
			
			// aapt resource value: 0x7f080032
			public const int CMDiabetEditTextWCD = 2131230770;
			
			// aapt resource value: 0x7f080029
			public const int CMDiabetEditTextWeight = 2131230761;
			
			// aapt resource value: 0x7f080026
			public const int CMDiabetLinearLayoutTP1 = 2131230758;
			
			// aapt resource value: 0x7f08003c
			public const int CMDiabetLinearLayoutTP2 = 2131230780;
			
			// aapt resource value: 0x7f080025
			public const int CMDiabetScrollViewTmMn = 2131230757;
			
			// aapt resource value: 0x7f080035
			public const int CMDiabetSpinnerSex = 2131230773;
			
			// aapt resource value: 0x7f08003b
			public const int CMDiabetSwitchActive = 2131230779;
			
			// aapt resource value: 0x7f080039
			public const int CMDiabetSwitchDaPb = 2131230777;
			
			// aapt resource value: 0x7f080038
			public const int CMDiabetSwitchHisBd = 2131230776;
			
			// aapt resource value: 0x7f080037
			public const int CMDiabetSwitchParnet = 2131230775;
			
			// aapt resource value: 0x7f08003a
			public const int CMDiabetSwitchSomk = 2131230778;
			
			// aapt resource value: 0x7f080027
			public const int CMDiabetTableLayoutMain = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int CMDiabetTableRowTp1 = 2131230760;
			
			// aapt resource value: 0x7f08002b
			public const int CMDiabetTableRowTp2 = 2131230763;
			
			// aapt resource value: 0x7f08002e
			public const int CMDiabetTableRowTp3 = 2131230766;
			
			// aapt resource value: 0x7f080031
			public const int CMDiabetTableRowTp4 = 2131230769;
			
			// aapt resource value: 0x7f080034
			public const int CMDiabetTableRowTp5 = 2131230772;
			
			// aapt resource value: 0x7f08002a
			public const int CMDiabetTextViewTm1 = 2131230762;
			
			// aapt resource value: 0x7f08002d
			public const int CMDiabetTextViewTm2 = 2131230765;
			
			// aapt resource value: 0x7f080030
			public const int CMDiabetTextViewTm3 = 2131230768;
			
			// aapt resource value: 0x7f080033
			public const int CMDiabetTextViewTm4 = 2131230771;
			
			// aapt resource value: 0x7f080036
			public const int CMDiabetTextViewTm7 = 2131230774;
			
			// aapt resource value: 0x7f08003f
			public const int CMTabHostImageViewPic = 2131230783;
			
			// aapt resource value: 0x7f080040
			public const int CMTabHostTextViewTilte = 2131230784;
			
			// aapt resource value: 0x7f080063
			public const int CPBNumberPickerWCS = 2131230819;
			
			// aapt resource value: 0x7f08001c
			public const int CalculatorMedicalHBtnCalc = 2131230748;
			
			// aapt resource value: 0x7f080009
			public const int CalculatorMedicalHEditTextAge = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int CalculatorMedicalHEditTextTall = 2131230733;
			
			// aapt resource value: 0x7f080011
			public const int CalculatorMedicalHEditTextWeight = 2131230737;
			
			// aapt resource value: 0x7f08000e
			public const int CalculatorMedicalHEditViewTall = 2131230734;
			
			// aapt resource value: 0x7f08001b
			public const int CalculatorMedicalHImageViewActive = 2131230747;
			
			// aapt resource value: 0x7f08000b
			public const int CalculatorMedicalHImageViewAge = 2131230731;
			
			// aapt resource value: 0x7f080017
			public const int CalculatorMedicalHImageViewSex = 2131230743;
			
			// aapt resource value: 0x7f08000f
			public const int CalculatorMedicalHImageViewTall = 2131230735;
			
			// aapt resource value: 0x7f080013
			public const int CalculatorMedicalHImageViewWeight = 2131230739;
			
			// aapt resource value: 0x7f080006
			public const int CalculatorMedicalHLinearLayoutPanel = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int CalculatorMedicalHScrollViewMain = 2131230725;
			
			// aapt resource value: 0x7f080019
			public const int CalculatorMedicalHSpinnerActive = 2131230745;
			
			// aapt resource value: 0x7f080015
			public const int CalculatorMedicalHSpinnerSex = 2131230741;
			
			// aapt resource value: 0x7f080007
			public const int CalculatorMedicalHTableLayoutMain = 2131230727;
			
			// aapt resource value: 0x7f080018
			public const int CalculatorMedicalHTableRowActive = 2131230744;
			
			// aapt resource value: 0x7f080008
			public const int CalculatorMedicalHTableRowAge = 2131230728;
			
			// aapt resource value: 0x7f080014
			public const int CalculatorMedicalHTableRowSex = 2131230740;
			
			// aapt resource value: 0x7f08000c
			public const int CalculatorMedicalHTableRowTall = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int CalculatorMedicalHTableRowWeight = 2131230736;
			
			// aapt resource value: 0x7f08001a
			public const int CalculatorMedicalHTextViewActive = 2131230746;
			
			// aapt resource value: 0x7f08000a
			public const int CalculatorMedicalHTextViewAge = 2131230730;
			
			// aapt resource value: 0x7f08001d
			public const int CalculatorMedicalHTextViewResult = 2131230749;
			
			// aapt resource value: 0x7f080016
			public const int CalculatorMedicalHTextViewSex = 2131230742;
			
			// aapt resource value: 0x7f080012
			public const int CalculatorMedicalHTextViewWeight = 2131230738;
			
			// aapt resource value: 0x7f080004
			public const int CalculatorMedicalLinearLayoutTp1 = 2131230724;
			
			// aapt resource value: 0x7f08001e
			public const int CalculatorMedicalLinearLayoutTp2 = 2131230750;
			
			// aapt resource value: 0x7f080024
			public const int CalculatorMedicalLinearLayoutTp3 = 2131230756;
			
			// aapt resource value: 0x7f080003
			public const int CalculatorMedicalTabHostMain = 2131230723;
			
			// aapt resource value: 0x7f08005e
			public const int HRBListViewData = 2131230814;
			
			// aapt resource value: 0x7f080077
			public const int HealthBtnOnOff = 2131230839;
			
			// aapt resource value: 0x7f080068
			public const int HealthChronometerMain = 2131230824;
			
			// aapt resource value: 0x7f080064
			public const int HealthFlipNumbersMainV = 2131230820;
			
			// aapt resource value: 0x7f08006c
			public const int HealthImageViewCaleri = 2131230828;
			
			// aapt resource value: 0x7f080076
			public const int HealthImageViewHeightKL = 2131230838;
			
			// aapt resource value: 0x7f08006f
			public const int HealthImageViewKiloMeter = 2131230831;
			
			// aapt resource value: 0x7f080072
			public const int HealthImageViewSpeed = 2131230834;
			
			// aapt resource value: 0x7f080069
			public const int HealthImageViewTimer = 2131230825;
			
			// aapt resource value: 0x7f080065
			public const int HealthLinearLayoutMTP = 2131230821;
			
			// aapt resource value: 0x7f080074
			public const int HealthScrollViewMainTVK = 2131230836;
			
			// aapt resource value: 0x7f080066
			public const int HealthTableLayoutMain = 2131230822;
			
			// aapt resource value: 0x7f08006a
			public const int HealthTableRowCaleri = 2131230826;
			
			// aapt resource value: 0x7f080073
			public const int HealthTableRowHeightKL = 2131230835;
			
			// aapt resource value: 0x7f08006d
			public const int HealthTableRowKiloMeter = 2131230829;
			
			// aapt resource value: 0x7f080070
			public const int HealthTableRowSpeed = 2131230832;
			
			// aapt resource value: 0x7f080067
			public const int HealthTableRowTimer = 2131230823;
			
			// aapt resource value: 0x7f08006b
			public const int HealthTextViewCaleri = 2131230827;
			
			// aapt resource value: 0x7f080075
			public const int HealthTextViewHeightKL = 2131230837;
			
			// aapt resource value: 0x7f08006e
			public const int HealthTextViewKiloMeter = 2131230830;
			
			// aapt resource value: 0x7f080071
			public const int HealthTextViewSpeed = 2131230833;
			
			// aapt resource value: 0x7f080089
			public const int HeartRateCSToastImageViewTM = 2131230857;
			
			// aapt resource value: 0x7f08008a
			public const int HeartRateCSToastTextViewTM = 2131230858;
			
			// aapt resource value: 0x7f080078
			public const int HeartRateImageViewAniTime = 2131230840;
			
			// aapt resource value: 0x7f08007e
			public const int HeartRateImageViewCountHR = 2131230846;
			
			// aapt resource value: 0x7f080082
			public const int HeartRateImageViewReport = 2131230850;
			
			// aapt resource value: 0x7f080086
			public const int HeartRateImageViewValueMain = 2131230854;
			
			// aapt resource value: 0x7f08007a
			public const int HeartRateLinearLayoutTM = 2131230842;
			
			// aapt resource value: 0x7f080088
			public const int HeartRateLinearLayoutWC = 2131230856;
			
			// aapt resource value: 0x7f080087
			public const int HeartRateNumberbarProTime = 2131230855;
			
			// aapt resource value: 0x7f080084
			public const int HeartRateScrollViewHRm = 2131230852;
			
			// aapt resource value: 0x7f080080
			public const int HeartRateScrollViewRp = 2131230848;
			
			// aapt resource value: 0x7f080079
			public const int HeartRateScrollViewTLMain = 2131230841;
			
			// aapt resource value: 0x7f080090
			public const int HeartRateTHHLinearLayoutEdu = 2131230864;
			
			// aapt resource value: 0x7f08008d
			public const int HeartRateTHHLinearLayoutNotes = 2131230861;
			
			// aapt resource value: 0x7f08008c
			public const int HeartRateTHHLinearLayoutOne = 2131230860;
			
			// aapt resource value: 0x7f08008e
			public const int HeartRateTHHScrollViewTVm1 = 2131230862;
			
			// aapt resource value: 0x7f080091
			public const int HeartRateTHHScrollViewTVm2 = 2131230865;
			
			// aapt resource value: 0x7f08008b
			public const int HeartRateTHHTabHostMain = 2131230859;
			
			// aapt resource value: 0x7f08008f
			public const int HeartRateTHHTextViewEdu = 2131230863;
			
			// aapt resource value: 0x7f080092
			public const int HeartRateTHHTextViewNote = 2131230866;
			
			// aapt resource value: 0x7f08007b
			public const int HeartRateTableLayoutMain = 2131230843;
			
			// aapt resource value: 0x7f08007c
			public const int HeartRateTableRowOne = 2131230844;
			
			// aapt resource value: 0x7f080083
			public const int HeartRateTableRowThree = 2131230851;
			
			// aapt resource value: 0x7f08007f
			public const int HeartRateTableRowTwo = 2131230847;
			
			// aapt resource value: 0x7f08007d
			public const int HeartRateTextViewCountHR = 2131230845;
			
			// aapt resource value: 0x7f080081
			public const int HeartRateTextViewReport = 2131230849;
			
			// aapt resource value: 0x7f080085
			public const int HeartRateTextViewVMHR = 2131230853;
			
			// aapt resource value: 0x7f08009c
			public const int LVDepLinearLayoutMain = 2131230876;
			
			// aapt resource value: 0x7f08009a
			public const int LayGVImageViewMain = 2131230874;
			
			// aapt resource value: 0x7f080099
			public const int LayGVLinearLayoutMmp = 2131230873;
			
			// aapt resource value: 0x7f08009b
			public const int LayGVTextViewTitle = 2131230875;
			
			// aapt resource value: 0x7f080096
			public const int LvCusLinearLayoutMtp = 2131230870;
			
			// aapt resource value: 0x7f080098
			public const int LvCusTextViewSummery = 2131230872;
			
			// aapt resource value: 0x7f080097
			public const int LvCusTextViewTitle = 2131230871;
			
			// aapt resource value: 0x7f0800a1
			public const int LvDepImageViewOC = 2131230881;
			
			// aapt resource value: 0x7f08009e
			public const int LvDepLinearLayoutTT = 2131230878;
			
			// aapt resource value: 0x7f08009d
			public const int LvDepTextViewNumber = 2131230877;
			
			// aapt resource value: 0x7f0800a0
			public const int LvDepTextViewText = 2131230880;
			
			// aapt resource value: 0x7f08009f
			public const int LvDepTextViewTitle = 2131230879;
			
			// aapt resource value: 0x7f0800a6
			public const int MassagersBtnMSHandel = 2131230886;
			
			// aapt resource value: 0x7f0800a4
			public const int MassagersImageViewVib = 2131230884;
			
			// aapt resource value: 0x7f0800a7
			public const int MassagersNumberPickerTime = 2131230887;
			
			// aapt resource value: 0x7f0800a5
			public const int MassagersTextViewPanel = 2131230885;
			
			// aapt resource value: 0x7f0800a8
			public const int MassagersToggleButtonRate = 2131230888;
			
			// aapt resource value: 0x7f0800b0
			public const int ProfileEditTextAge = 2131230896;
			
			// aapt resource value: 0x7f0800ac
			public const int ProfileEditTextName = 2131230892;
			
			// aapt resource value: 0x7f0800b3
			public const int ProfileEditTextTall = 2131230899;
			
			// aapt resource value: 0x7f0800b6
			public const int ProfileEditTextWeight = 2131230902;
			
			// aapt resource value: 0x7f0800ab
			public const int ProfileImageViewNA = 2131230891;
			
			// aapt resource value: 0x7f0800a9
			public const int ProfileLinearLayoutTp1 = 2131230889;
			
			// aapt resource value: 0x7f0800ad
			public const int ProfileLinearLayoutTp2 = 2131230893;
			
			// aapt resource value: 0x7f0800aa
			public const int ProfileLinearLayoutTpp1 = 2131230890;
			
			// aapt resource value: 0x7f0800be
			public const int ProfileSCToastTextViewTS = 2131230910;
			
			// aapt resource value: 0x7f0800bc
			public const int ProfileSpinnerActive = 2131230908;
			
			// aapt resource value: 0x7f0800b9
			public const int ProfileSpinnerSex = 2131230905;
			
			// aapt resource value: 0x7f0800ae
			public const int ProfileTableLayoutMain = 2131230894;
			
			// aapt resource value: 0x7f0800af
			public const int ProfileTableRowA = 2131230895;
			
			// aapt resource value: 0x7f0800bb
			public const int ProfileTableRowAC = 2131230907;
			
			// aapt resource value: 0x7f0800b8
			public const int ProfileTableRowS = 2131230904;
			
			// aapt resource value: 0x7f0800b2
			public const int ProfileTableRowT = 2131230898;
			
			// aapt resource value: 0x7f0800b5
			public const int ProfileTableRowW = 2131230901;
			
			// aapt resource value: 0x7f0800b1
			public const int ProfileTextViewA = 2131230897;
			
			// aapt resource value: 0x7f0800bd
			public const int ProfileTextViewAC = 2131230909;
			
			// aapt resource value: 0x7f0800ba
			public const int ProfileTextViewS = 2131230906;
			
			// aapt resource value: 0x7f0800b4
			public const int ProfileTextViewT = 2131230900;
			
			// aapt resource value: 0x7f0800b7
			public const int ProfileTextViewW = 2131230903;
			
			// aapt resource value: 0x7f08005c
			public const int SportListViewMain = 2131230812;
			
			// aapt resource value: 0x7f080060
			public const int WHListViewData = 2131230816;
			
			// aapt resource value: 0x7f080000
			public const int calligraphy_tag_id = 2131230720;
			
			// aapt resource value: 0x7f0800a2
			public const int content_frame = 2131230882;
			
			// aapt resource value: 0x7f0800a3
			public const int gridView1 = 2131230883;
			
			// aapt resource value: 0x7f080001
			public const int invisible = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int visible = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlarmMedical = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CalculatorMedical = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CalculatorMedicalTabHostCustom = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CBPInputDataSHRWT = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ControlBodyPosition = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CPBInputHome = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CPBInputSleepy = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CPBInputWaterCafi = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Health = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int HeartRate = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int HeartRateCSToast = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int HeartRateTHHelp = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int HelpAbout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int LayoutCBPLSV = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int LayoutMGv = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ListViewCMDep = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Main = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Massagers = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int MassagersCustom = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Profile = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ProfileCSToast = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int Beep1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Beep2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Beep3 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int BeepError = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Click1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Click2 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int HeartRate = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int LF = 2131034119;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Edu1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Edu2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Edu3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Edu4 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Edu5 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int HelpAppHR1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int HelpAppHR2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int HelpAppHR3 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int HelpAppHR4 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int HelpAppHR5 = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int NumberProgressBar_Beauty_Red = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int NumberProgressBar_Default = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int NumberProgressBar_Funny_Orange = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int NumberProgressBar_Grace_Yellow = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int NumberProgressBar_Passing_Green = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int NumberProgressBar_Relax_Blue = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int NumberProgressBar_Twinkle_Night = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int NumberProgressBar_Warning_Red = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int ThemeaMain = 2131165192;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int UISettingP = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AnimatedCircleLoadingView = new int[] {
					2130771980,
					2130771981};
			
			// aapt resource value: 0
			public const int AnimatedCircleLoadingView_mainColor = 0;
			
			// aapt resource value: 1
			public const int AnimatedCircleLoadingView_secondaryColor = 1;
			
			public static int[] NumberProgressBar = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public const int NumberProgressBar_max = 1;
			
			// aapt resource value: 0
			public const int NumberProgressBar_progress = 0;
			
			// aapt resource value: 4
			public const int NumberProgressBar_progress_reached_bar_height = 4;
			
			// aapt resource value: 3
			public const int NumberProgressBar_progress_reached_color = 3;
			
			// aapt resource value: 7
			public const int NumberProgressBar_progress_text_color = 7;
			
			// aapt resource value: 8
			public const int NumberProgressBar_progress_text_offset = 8;
			
			// aapt resource value: 6
			public const int NumberProgressBar_progress_text_size = 6;
			
			// aapt resource value: 9
			public const int NumberProgressBar_progress_text_visibility = 9;
			
			// aapt resource value: 5
			public const int NumberProgressBar_progress_unreached_bar_height = 5;
			
			// aapt resource value: 2
			public const int NumberProgressBar_progress_unreached_color = 2;
			
			public static int[] Themes = new int[] {
					2130771978};
			
			// aapt resource value: 0
			public const int Themes_numberProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
